AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VPCCidrBlock:
    Description: Enter the CIDR block for the VPC
    Type: String
    Default: "10.0.0.0/16"

  PublicSubnetCidrBlock:
    Description: Enter the CIDR block for the Public Subnet
    Type: String
    Default: "10.0.1.0/24"

  PrivateSubnetCidrBlock:
    Description: Enter the CIDR block for the Private Subnet
    Type: String
    Default: "10.0.2.0/24"

  EC2KeyName:
    Description: Name of the EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName

  EC2ImageId:
    Description: ID of the Amazon Machine Image (AMI)
    Type: AWS::EC2::Image::Id
    Default: "ami-06d4b7182ac3480fa" # Default AMI ID

  EC2InstanceType:
    Description: Type of EC2 Instance
    Type: String
    Default: "t2.micro" # Default instance type

  MyIP:
    Description: Your IP Address
    Type: String
    Default: "0.0.0.0/0" # Change this default to your specific IP

Resources:
  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://mycfbucket1116.s3.amazonaws.com/vpcstack.yaml"
      Parameters:
        VPCCidrBlock: !Ref VPCCidrBlock
        PublicSubnetCidrBlock: !Ref PublicSubnetCidrBlock
        PrivateSubnetCidrBlock: !Ref PrivateSubnetCidrBlock

  EC2InstanceStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://mycfbucket1116.s3.amazonaws.com/Ec2Instancestack.yaml"
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.MyVPC
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnet
        EC2KeyName: !Ref EC2KeyName
        EC2ImageId: !Ref EC2ImageId
        EC2InstanceType: !Ref EC2InstanceType
        MyIP: !Ref MyIP
